### ISSUE TITLE
Can't run locally

### ISSUE THREAD

**Issue by adelgado** [tramaLabs/rest#31]
I've installed all the dependencies on a newly cloned copy of this repo and tried to run it with `npm start`. I get the following errors:

```
➜  rest git:(master) ✗ npm start

> trama@0.0.0 start /Users/elros/projects/trama/rest
> node .

/Users/elros/projects/trama/rest/node_modules/node-summary/lib/summary.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'lodash'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Module._extensions..js (module.js:584:10)
```

Is there any extra step I must take?

**Comment by diegohaz** [comment]
That's a problem with node-summary. We need to downgrade its version.
https://github.com/jbrooksuk/node-summary/issues/36

**Comment by adelgado** [comment]
It seems they simply chose to publish code as per the latest edition of JavaScript. Shouldn't we run everything through a transpiler when consuming it anyhow?

**Comment by diegohaz** [comment]
The easiest solution is probably just putting the exact version on package.json.
```diff
"dependencies": {
    ...
-   "node-summary": "^1.1.0",
+   "node-summary": "1.1.0",
    ...
  }
```
