### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by francisrod01** [tramaLabs/rest#32]
```
$ npm run dev

> trama@0.0.0 dev /home/paneladm/projects/express-rest
> nodemon -i '*.test.js' .

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node .`
/home/paneladm/projects/express-rest/node_modules/node-summary/lib/summary.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'lodash'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/paneladm/projects/express-rest/node_modules/babel-register/lib/node.js:152:7)
```

**Comment by adelgado** [comment]
Thank you for taking the time to submit this issue. This is a known issue, which is being tracked on #31 .
